// <auto-generated />
namespace Ecommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ajout_des_sous_categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajout_des_sous_categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201903111129438_Ajout_des_sous_categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
